### ISSUE TITLE
Wrong URL in DRF for images when running through Loophole

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas-app-explorer#159]
When running in Loophole, images are having the URL https://127.0.0.1 instead of the original URL. It looks like the solution is to set 

USE_X_FORWARDED_HOST=True in the config

This should be fine to use for all settings, though may need to be configurable.

**Comment by ssciolla** [comment]
Relevant docs: https://docs.djangoproject.com/en/4.0/ref/settings/#use-x-forwarded-port

Django says "This should only be enabled if a proxy which sets this header is in use." Does this also describe our deployment environments? If so, this is probably fine; otherwise, we should make it configurable. It can default to True if you want.

**Comment by jonespm** [comment]
I haven't tested it on Openshift. I could make it configurable just incase. I know that this was an issue we wanted to look at for X-FORWARDED-FOR on https://github.com/tl-its-umich-edu/remote-office-hours-queue/issues/359 but that's a slightly different issue. I do know that one did work.
